### ISSUE TITLE
Should the first bar under Deck Reliability be labeled <0?

### ISSUE THREAD

**Issue by scalisi** [epoblaguev/gloomhaven-perk-calculator#23]
Should the first bar in the Deck Reliability chart be labeled **<0** instead of **≤1**?

Thanks a lot for publishing the Gloomhaven Perk Calculator. It's super helpful.

**Comment by epoblaguev** [comment]
Good point, it would probably make more sense to rename the three columns to something like 'Damage Decreased', 'No Change', and 'Damage Increased'.
