### ISSUE TITLE
Pull Request: Frosthaven Starter Classes

### ISSUE THREAD

**Issue by scottmk** [epoblaguev/gloomhaven-perk-calculator#55]
Hi,

I love your calculator; thanks for making this.

I have a pull request ready to submit for the Frosthaven Starter Classes, but I can't seem to push to a remote branch in order to create the PR. Could you give me permission to do so that I could share this update with you?

Thanks!

\- Michael

**Comment by scottmk** [comment]
I closed this because I realized that I could just make a PR from a fork.

**Comment by epoblaguev** [comment]
Thanks! I'll try to check the PR and pull it in the next couple of days.
